-- abyss.nvim — highlights.lua
-- Full highlight definitions: core Vim, Treesitter, LSP, and all major plugins.

local M = {}

---@param groups table<string, table>
local function set(groups)
  for name, opts in pairs(groups) do
    vim.api.nvim_set_hl(0, name, opts)
  end
end

---@param c table  palette colors
---@param opts table  user config
function M.apply(c, opts)
  local italic = opts.italic_comments and "italic" or nil
  local bold   = opts.bold_keywords   and "bold"   or nil

  -- ─── Editor Core ───────────────────────────────────────────────────────────
  set({
    Normal          = { fg = c.fg,        bg = c.bg },
    NormalFloat     = { fg = c.fg,        bg = c.bg2 },
    NormalNC        = { fg = c.fg1,       bg = c.bg },
    FloatBorder     = { fg = c.bg4,       bg = c.bg2 },
    FloatTitle      = { fg = c.accent,    bg = c.bg2 },
    FloatFooter     = { fg = c.fg2,       bg = c.bg2 },

    Cursor          = { fg = c.bg,        bg = c.fg },
    CursorIM        = { fg = c.bg,        bg = c.fg },
    CursorLine      = { bg = c.cursorline },
    CursorColumn    = { bg = c.cursorline },
    CursorLineNr    = { fg = c.linenr_cur, bold = true },
    CursorLineFold  = { fg = c.linenr_cur },
    CursorLineSign  = { bg = c.cursorline },

    LineNr          = { fg = c.linenr },
    LineNrAbove     = { fg = c.linenr },
    LineNrBelow     = { fg = c.linenr },

    SignColumn      = { fg = c.fg3,       bg = c.none },
    ColorColumn     = { bg = c.bg3 },
    Conceal         = { fg = c.fg4 },
    FoldColumn      = { fg = c.fg3,       bg = c.none },
    Folded          = { fg = c.fg2,       bg = c.bg3 },

    StatusLine      = { fg = c.fg1,       bg = c.bg1 },
    StatusLineNC    = { fg = c.fg3,       bg = c.bg1 },
    TabLine         = { fg = c.fg2,       bg = c.bg1 },
    TabLineFill     = { fg = c.none,      bg = c.bg1 },
    TabLineSel      = { fg = c.fg,        bg = c.bg },

    WinBar          = { fg = c.fg2,       bg = c.bg },
    WinBarNC        = { fg = c.fg3,       bg = c.bg },
    WinSeparator    = { fg = c.bg4 },

    Pmenu           = { fg = c.fg,        bg = c.bg2 },
    PmenuSel        = { fg = c.fg,        bg = c.selection },
    PmenuSbar       = { bg = c.bg3 },
    PmenuThumb      = { bg = c.accent },
    PmenuKind       = { fg = c.type_,     bg = c.bg2 },
    PmenuKindSel    = { fg = c.type_,     bg = c.selection },
    PmenuExtra      = { fg = c.fg2,       bg = c.bg2 },
    PmenuExtraSel   = { fg = c.fg1,       bg = c.selection },

    Visual          = { bg = c.selection },
    VisualNOS       = { bg = c.selection },

    Search          = { fg = c.fg,        bg = c.match },
    IncSearch       = { fg = c.bg,        bg = c.accent },
    CurSearch       = { fg = c.bg,        bg = c.accent2 },
    Substitute      = { fg = c.bg,        bg = c.error_ },

    MatchParen      = { fg = c.accent2,   bold = true, underline = true },

    Directory       = { fg = c.accent2 },
    Title           = { fg = c.accent,    bold = true },
    EndOfBuffer     = { fg = c.bg4 },
    NonText         = { fg = c.fg4 },
    Whitespace      = { fg = c.bg5 },
    SpecialKey      = { fg = c.bg5 },

    WildMenu        = { fg = c.fg,        bg = c.match_cur },
    QuickFixLine    = { fg = c.fn,        bold = true },

    MsgArea         = { fg = c.fg1 },
    MsgSeparator    = { fg = c.bg4 },
    MoreMsg         = { fg = c.ok,        bold = true },
    Question        = { fg = c.hint },
    ErrorMsg        = { fg = c.error_ },
    WarningMsg      = { fg = c.warn },

    SpellBad        = { undercurl = true, sp = c.error_ },
    SpellCap        = { undercurl = true, sp = c.warn },
    SpellLocal      = { undercurl = true, sp = c.info },
    SpellRare       = { undercurl = true, sp = c.hint },

    -- ─── Syntax (classic) ─────────────────────────────────────────────────
    Comment         = { fg = c.fg3,       italic = italic },
    SpecialComment  = { fg = c.fg3,       italic = italic },

    Constant        = { fg = c.constant },
    String          = { fg = c.string_ },
    Character       = { fg = c.string_ },
    Number          = { fg = c.number },
    Boolean         = { fg = c.number },
    Float           = { fg = c.number },

    Identifier      = { fg = c.variable },
    Function        = { fg = c.fn },

    Statement       = { fg = c.keyword,   bold = bold },
    Conditional     = { fg = c.keyword,   bold = bold },
    Repeat          = { fg = c.keyword,   bold = bold },
    Label           = { fg = c.keyword },
    Operator        = { fg = c.operator },
    Keyword         = { fg = c.keyword,   bold = bold },
    Exception       = { fg = c.keyword },

    PreProc         = { fg = c.macro },
    Include         = { fg = c.macro },
    Define          = { fg = c.macro },
    Macro           = { fg = c.macro },
    PreCondit       = { fg = c.macro },

    Type            = { fg = c.type_ },
    StorageClass    = { fg = c.keyword },
    Structure       = { fg = c.type_ },
    Typedef         = { fg = c.type_ },

    Special         = { fg = c.special },
    SpecialChar     = { fg = c.escape },
    Tag             = { fg = c.attr },
    Delimiter       = { fg = c.punct },

    Bold            = { bold = true },
    Italic          = { italic = true },
    Underlined      = { underline = true },
    Ignore          = { fg = c.fg4 },
    Error           = { fg = c.error_,    bold = true },
    Todo            = { fg = c.bg,        bg = c.warn, bold = true },
  })

  -- ─── Treesitter ────────────────────────────────────────────────────────────
  set({
    ["@comment"]                    = { fg = c.fg3,     italic = italic },
    ["@comment.documentation"]      = { fg = c.fg2,     italic = italic },
    ["@comment.todo"]               = { fg = c.bg,      bg = c.warn, bold = true },
    ["@comment.note"]               = { fg = c.bg,      bg = c.hint, bold = true },
    ["@comment.warning"]            = { fg = c.bg,      bg = c.warn, bold = true },
    ["@comment.error"]              = { fg = c.bg,      bg = c.error_, bold = true },

    ["@keyword"]                    = { fg = c.keyword, bold = bold },
    ["@keyword.function"]           = { fg = c.keyword, bold = bold },
    ["@keyword.operator"]           = { fg = c.keyword },
    ["@keyword.return"]             = { fg = c.keyword, bold = bold },
    ["@keyword.import"]             = { fg = c.macro },
    ["@keyword.conditional"]        = { fg = c.keyword, bold = bold },
    ["@keyword.conditional.ternary"]= { fg = c.operator },
    ["@keyword.repeat"]             = { fg = c.keyword },
    ["@keyword.exception"]          = { fg = c.keyword },
    ["@keyword.modifier"]           = { fg = c.keyword },
    ["@keyword.type"]               = { fg = c.keyword },
    ["@keyword.coroutine"]          = { fg = c.keyword },
    ["@keyword.directive"]          = { fg = c.macro },
    ["@keyword.directive.define"]   = { fg = c.macro },

    ["@variable"]                   = { fg = c.variable },
    ["@variable.builtin"]           = { fg = c.accent2 },
    ["@variable.parameter"]         = { fg = c.param },
    ["@variable.parameter.builtin"] = { fg = c.accent2 },
    ["@variable.member"]            = { fg = c.field },

    ["@function"]                   = { fg = c.fn },
    ["@function.builtin"]           = { fg = c.accent2 },
    ["@function.call"]              = { fg = c.fn },
    ["@function.macro"]             = { fg = c.macro },
    ["@function.method"]            = { fg = c.fn },
    ["@function.method.call"]       = { fg = c.fn },

    ["@constructor"]                = { fg = c.type_ },

    ["@type"]                       = { fg = c.type_ },
    ["@type.builtin"]               = { fg = c.type_ },
    ["@type.definition"]            = { fg = c.type_ },
    ["@type.qualifier"]             = { fg = c.keyword },

    ["@string"]                     = { fg = c.string_ },
    ["@string.documentation"]       = { fg = c.string2, italic = italic },
    ["@string.regexp"]              = { fg = c.regexp },
    ["@string.escape"]              = { fg = c.escape },
    ["@string.special"]             = { fg = c.escape },
    ["@string.special.symbol"]      = { fg = c.attr },
    ["@string.special.url"]         = { fg = c.info, underline = true },
    ["@string.special.path"]        = { fg = c.info },

    ["@character"]                  = { fg = c.string_ },
    ["@character.special"]          = { fg = c.escape },

    ["@number"]                     = { fg = c.number },
    ["@number.float"]               = { fg = c.number },
    ["@boolean"]                    = { fg = c.number, bold = bold },

    ["@constant"]                   = { fg = c.constant },
    ["@constant.builtin"]           = { fg = c.number },
    ["@constant.macro"]             = { fg = c.macro },

    ["@operator"]                   = { fg = c.operator },
    ["@punctuation.bracket"]        = { fg = c.punct },
    ["@punctuation.delimiter"]      = { fg = c.fg2 },
    ["@punctuation.special"]        = { fg = c.punct },

    ["@attribute"]                  = { fg = c.attr },
    ["@attribute.builtin"]          = { fg = c.attr },

    ["@namespace"]                  = { fg = c.namespace },
    ["@module"]                     = { fg = c.namespace },
    ["@module.builtin"]             = { fg = c.accent2 },

    ["@label"]                      = { fg = c.attr },

    -- Markup (markdown, rst, etc.)
    ["@markup.heading.1"]           = { fg = c.accent,   bold = true },
    ["@markup.heading.2"]           = { fg = c.fn,       bold = true },
    ["@markup.heading.3"]           = { fg = c.type_,    bold = true },
    ["@markup.heading.4"]           = { fg = c.string_,  bold = true },
    ["@markup.heading.5"]           = { fg = c.number,   bold = true },
    ["@markup.heading.6"]           = { fg = c.fg1,      bold = true },
    ["@markup.raw"]                 = { fg = c.string_,  bg = c.bg3 },
    ["@markup.raw.block"]           = { fg = c.string_ },
    ["@markup.quote"]               = { fg = c.fg2,      italic = true },
    ["@markup.math"]                = { fg = c.number },
    ["@markup.link"]                = { fg = c.info,     underline = true },
    ["@markup.link.url"]            = { fg = c.info,     underline = true },
    ["@markup.link.label"]          = { fg = c.accent2 },
    ["@markup.list"]                = { fg = c.accent },
    ["@markup.list.checked"]        = { fg = c.ok },
    ["@markup.list.unchecked"]      = { fg = c.fg2 },
    ["@markup.strong"]              = { bold = true },
    ["@markup.italic"]              = { italic = true },
    ["@markup.strikethrough"]       = { strikethrough = true },
    ["@markup.underline"]           = { underline = true },

    -- HTML/JSX tags
    ["@tag"]                        = { fg = c.attr },
    ["@tag.attribute"]              = { fg = c.field },
    ["@tag.builtin"]                = { fg = c.keyword },
    ["@tag.delimiter"]              = { fg = c.fg2 },

    -- Diff
    ["@diff.plus"]                  = { fg = c.git_add },
    ["@diff.minus"]                 = { fg = c.git_delete },
    ["@diff.delta"]                 = { fg = c.git_change },
  })

  -- ─── LSP Semantic Tokens ───────────────────────────────────────────────────
  set({
    ["@lsp.type.class"]          = { link = "@type" },
    ["@lsp.type.comment"]        = { link = "@comment" },
    ["@lsp.type.decorator"]      = { link = "@attribute" },
    ["@lsp.type.enum"]           = { link = "@type" },
    ["@lsp.type.enumMember"]     = { link = "@constant" },
    ["@lsp.type.event"]          = { link = "@variable.member" },
    ["@lsp.type.function"]       = { link = "@function" },
    ["@lsp.type.interface"]      = { fg = c.type_ },
    ["@lsp.type.keyword"]        = { link = "@keyword" },
    ["@lsp.type.macro"]          = { link = "@constant.macro" },
    ["@lsp.type.method"]         = { link = "@function.method" },
    ["@lsp.type.modifier"]       = { link = "@keyword.modifier" },
    ["@lsp.type.namespace"]      = { link = "@module" },
    ["@lsp.type.number"]         = { link = "@number" },
    ["@lsp.type.operator"]       = { link = "@operator" },
    ["@lsp.type.parameter"]      = { link = "@variable.parameter" },
    ["@lsp.type.property"]       = { link = "@variable.member" },
    ["@lsp.type.regexp"]         = { link = "@string.regexp" },
    ["@lsp.type.string"]         = { link = "@string" },
    ["@lsp.type.struct"]         = { link = "@type" },
    ["@lsp.type.type"]           = { link = "@type" },
    ["@lsp.type.typeParameter"]  = { fg = c.type_ },
    ["@lsp.type.variable"]       = { link = "@variable" },
    ["@lsp.mod.deprecated"]      = { strikethrough = true },
    ["@lsp.mod.readonly"]        = { fg = c.constant },
    ["@lsp.mod.static"]          = { italic = true },
    ["@lsp.mod.defaultLibrary"]  = { fg = c.accent2 },
  })

  -- ─── LSP Diagnostics ───────────────────────────────────────────────────────
  set({
    DiagnosticError            = { fg = c.error_ },
    DiagnosticWarn             = { fg = c.warn },
    DiagnosticInfo             = { fg = c.info },
    DiagnosticHint             = { fg = c.hint },
    DiagnosticOk               = { fg = c.ok },
    DiagnosticUnnecessary      = { fg = c.fg3, italic = true },
    DiagnosticDeprecated       = { fg = c.fg3, strikethrough = true },

    DiagnosticVirtualTextError = { fg = c.error_, bg = c.bg1, italic = italic },
    DiagnosticVirtualTextWarn  = { fg = c.warn,   bg = c.bg1, italic = italic },
    DiagnosticVirtualTextInfo  = { fg = c.info,   bg = c.bg1, italic = italic },
    DiagnosticVirtualTextHint  = { fg = c.hint,   bg = c.bg1, italic = italic },
    DiagnosticVirtualTextOk    = { fg = c.ok,     bg = c.bg1, italic = italic },

    DiagnosticUnderlineError   = { undercurl = true, sp = c.error_ },
    DiagnosticUnderlineWarn    = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo    = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint    = { undercurl = true, sp = c.hint },

    DiagnosticSignError        = { fg = c.error_ },
    DiagnosticSignWarn         = { fg = c.warn },
    DiagnosticSignInfo         = { fg = c.info },
    DiagnosticSignHint         = { fg = c.hint },

    LspReferenceText           = { bg = c.bg3 },
    LspReferenceRead           = { bg = c.bg3 },
    LspReferenceWrite          = { bg = c.bg3, underline = true },
    LspSignatureActiveParameter= { fg = c.param, underline = true },
    LspCodeLens                = { fg = c.fg3, italic = true },
    LspCodeLensSeparator       = { fg = c.bg4 },
    LspInlayHint               = { fg = c.fg3, bg = c.bg1, italic = true },
  })

  -- ─── Diff ─────────────────────────────────────────────────────────────────
  set({
    DiffAdd    = { fg = c.git_add,    bg = "#0d1f14" },
    DiffChange = { fg = c.git_change, bg = "#1c1708" },
    DiffDelete = { fg = c.git_delete, bg = "#1f0d14" },
    DiffText   = { fg = c.git_text,   bg = "#0d1828" },
    diffAdded  = { link = "DiffAdd" },
    diffRemoved= { link = "DiffDelete" },
    diffChanged= { link = "DiffChange" },
    diffFile   = { fg = c.info },
    diffNewFile= { fg = c.ok },
    diffOldFile= { fg = c.error_ },
    diffLine   = { fg = c.fg3 },
  })

  -- ─── GitSigns ─────────────────────────────────────────────────────────────
  set({
    GitSignsAdd            = { fg = c.git_add },
    GitSignsChange         = { fg = c.git_change },
    GitSignsDelete         = { fg = c.git_delete },
    GitSignsTopdelete      = { fg = c.git_delete },
    GitSignsChangedelete   = { fg = c.git_change },
    GitSignsUntracked      = { fg = c.fg3 },
    GitSignsAddNr          = { link = "GitSignsAdd" },
    GitSignsChangeNr       = { link = "GitSignsChange" },
    GitSignsDeleteNr       = { link = "GitSignsDelete" },
    GitSignsAddLn          = { bg = "#0d1f14" },
    GitSignsChangeLn       = { bg = "#1c1708" },
    GitSignsDeleteLn       = { bg = "#1f0d14" },
    GitSignsCurrentLineBlame = { fg = c.fg4, italic = true },
    GitSignsAddInline      = { fg = c.bg, bg = c.git_add },
    GitSignsDeleteInline   = { fg = c.bg, bg = c.git_delete },
    GitSignsChangeInline   = { fg = c.bg, bg = c.git_change },
  })

  -- ─── blink.cmp ────────────────────────────────────────────────────────────
  set({
    BlinkCmpMenu           = { fg = c.fg,    bg = c.bg2 },
    BlinkCmpMenuBorder     = { fg = c.bg4,   bg = c.bg2 },
    BlinkCmpMenuSelection  = { fg = c.fg,    bg = c.selection },
    BlinkCmpScrollBarThumb = { bg = c.accent },
    BlinkCmpScrollBarGutter= { bg = c.bg3 },

    BlinkCmpLabel          = { fg = c.fg },
    BlinkCmpLabelDeprecated= { fg = c.fg3,   strikethrough = true },
    BlinkCmpLabelMatch     = { fg = c.accent2, bold = true },
    BlinkCmpLabelDetail    = { fg = c.fg2 },
    BlinkCmpLabelDescription = { fg = c.fg3 },

    BlinkCmpKind           = { fg = c.accent },
    BlinkCmpKindText       = { fg = c.fg2 },
    BlinkCmpKindMethod     = { fg = c.fn },
    BlinkCmpKindFunction   = { fg = c.fn },
    BlinkCmpKindConstructor= { fg = c.type_ },
    BlinkCmpKindField      = { fg = c.field },
    BlinkCmpKindVariable   = { fg = c.variable },
    BlinkCmpKindClass      = { fg = c.type_ },
    BlinkCmpKindInterface  = { fg = c.type_ },
    BlinkCmpKindModule     = { fg = c.namespace },
    BlinkCmpKindProperty   = { fg = c.field },
    BlinkCmpKindUnit       = { fg = c.number },
    BlinkCmpKindValue      = { fg = c.number },
    BlinkCmpKindEnum       = { fg = c.type_ },
    BlinkCmpKindKeyword    = { fg = c.keyword },
    BlinkCmpKindSnippet    = { fg = c.string_ },
    BlinkCmpKindColor      = { fg = c.attr },
    BlinkCmpKindFile       = { fg = c.info },
    BlinkCmpKindReference  = { fg = c.constant },
    BlinkCmpKindFolder     = { fg = c.info },
    BlinkCmpKindEnumMember = { fg = c.constant },
    BlinkCmpKindConstant   = { fg = c.constant },
    BlinkCmpKindStruct     = { fg = c.type_ },
    BlinkCmpKindEvent      = { fg = c.attr },
    BlinkCmpKindOperator   = { fg = c.operator },
    BlinkCmpKindTypeParameter = { fg = c.type_ },

    BlinkCmpDoc            = { fg = c.fg,    bg = c.bg2 },
    BlinkCmpDocBorder      = { fg = c.bg4,   bg = c.bg2 },
    BlinkCmpDocSeparator   = { fg = c.bg4 },
    BlinkCmpDocCursorLine  = { bg = c.bg3 },

    BlinkCmpSignatureHelp       = { fg = c.fg,   bg = c.bg2 },
    BlinkCmpSignatureHelpBorder = { fg = c.bg4,  bg = c.bg2 },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.param, underline = true },

    BlinkCmpGhostText      = { fg = c.fg4 },
  })

  -- ─── nvim-cmp (fallback) ──────────────────────────────────────────────────
  set({
    CmpItemAbbr           = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.fg3, strikethrough = true },
    CmpItemAbbrMatch      = { fg = c.accent2, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.accent2 },
    CmpItemMenu           = { fg = c.fg2 },
    CmpItemKind           = { fg = c.accent },
    CmpItemKindText       = { link = "BlinkCmpKindText" },
    CmpItemKindMethod     = { link = "BlinkCmpKindMethod" },
    CmpItemKindFunction   = { link = "BlinkCmpKindFunction" },
    CmpItemKindConstructor= { link = "BlinkCmpKindConstructor" },
    CmpItemKindField      = { link = "BlinkCmpKindField" },
    CmpItemKindVariable   = { link = "BlinkCmpKindVariable" },
    CmpItemKindClass      = { link = "BlinkCmpKindClass" },
    CmpItemKindInterface  = { link = "BlinkCmpKindInterface" },
    CmpItemKindModule     = { link = "BlinkCmpKindModule" },
    CmpItemKindProperty   = { link = "BlinkCmpKindProperty" },
    CmpItemKindUnit       = { link = "BlinkCmpKindUnit" },
    CmpItemKindValue      = { link = "BlinkCmpKindValue" },
    CmpItemKindEnum       = { link = "BlinkCmpKindEnum" },
    CmpItemKindKeyword    = { link = "BlinkCmpKindKeyword" },
    CmpItemKindSnippet    = { link = "BlinkCmpKindSnippet" },
    CmpItemKindColor      = { link = "BlinkCmpKindColor" },
    CmpItemKindFile       = { link = "BlinkCmpKindFile" },
    CmpItemKindReference  = { link = "BlinkCmpKindReference" },
    CmpItemKindFolder     = { link = "BlinkCmpKindFolder" },
    CmpItemKindEnumMember = { link = "BlinkCmpKindEnumMember" },
    CmpItemKindConstant   = { link = "BlinkCmpKindConstant" },
    CmpItemKindStruct     = { link = "BlinkCmpKindStruct" },
    CmpItemKindEvent      = { link = "BlinkCmpKindEvent" },
    CmpItemKindOperator   = { link = "BlinkCmpKindOperator" },
    CmpItemKindTypeParameter = { link = "BlinkCmpKindTypeParameter" },
    CmpItemKindCopilot    = { fg = c.ok },
  })

  -- ─── fzf-lua ──────────────────────────────────────────────────────────────
  set({
    FzfLuaNormal        = { fg = c.fg,      bg = c.bg2 },
    FzfLuaBorder        = { fg = c.bg4,     bg = c.bg2 },
    FzfLuaTitle         = { fg = c.accent,  bg = c.bg2, bold = true },
    FzfLuaPreviewNormal = { fg = c.fg,      bg = c.bg },
    FzfLuaPreviewBorder = { fg = c.bg4,     bg = c.bg },
    FzfLuaPreviewTitle  = { fg = c.fn,      bg = c.bg },
    FzfLuaScrollFloat   = { fg = c.bg4 },
    FzfLuaScrollChars   = { fg = c.accent },
    FzfLuaHeaderBind    = { fg = c.type_ },
    FzfLuaHeaderText    = { fg = c.fg1 },
    FzfLuaPathColNr     = { fg = c.number,  bold = true },
    FzfLuaPathLineNr    = { fg = c.fn,      bold = true },
    FzfLuaBufName       = { fg = c.info },
    FzfLuaBufNr         = { fg = c.number },
    FzfLuaBufFlagCur    = { fg = c.accent2 },
    FzfLuaBufFlagAlt    = { fg = c.fg2 },
    FzfLuaTabTitle      = { fg = c.fn },
    FzfLuaTabMarker     = { fg = c.accent2 },
    FzfLuaDirIcon       = { fg = c.info },
    FzfLuaLiveSym       = { fg = c.attr },
  })

  -- ─── Telescope ────────────────────────────────────────────────────────────
  set({
    TelescopeNormal         = { fg = c.fg,     bg = c.bg2 },
    TelescopeBorder         = { fg = c.bg4,    bg = c.bg2 },
    TelescopeTitle          = { fg = c.accent, bg = c.bg2, bold = true },
    TelescopePromptNormal   = { fg = c.fg,     bg = c.bg3 },
    TelescopePromptBorder   = { fg = c.bg5,    bg = c.bg3 },
    TelescopePromptTitle    = { fg = c.fn,     bg = c.bg3, bold = true },
    TelescopePromptPrefix   = { fg = c.accent2 },
    TelescopePromptCounter  = { fg = c.fg3 },
    TelescopePreviewNormal  = { fg = c.fg,     bg = c.bg },
    TelescopePreviewBorder  = { fg = c.bg4,    bg = c.bg },
    TelescopePreviewTitle   = { fg = c.type_,  bg = c.bg, bold = true },
    TelescopeResultsNormal  = { fg = c.fg,     bg = c.bg2 },
    TelescopeResultsBorder  = { fg = c.bg4,    bg = c.bg2 },
    TelescopeResultsTitle   = { fg = c.fg3,    bg = c.bg2 },
    TelescopeResultsDiffAdd    = { fg = c.git_add },
    TelescopeResultsDiffChange = { fg = c.git_change },
    TelescopeResultsDiffDelete = { fg = c.git_delete },
    TelescopeResultsDiffUntracked = { fg = c.fg3 },
    TelescopeMatching       = { fg = c.accent2, bold = true },
    TelescopeSelection      = { fg = c.fg,     bg = c.selection },
    TelescopeSelectionCaret = { fg = c.accent2, bg = c.selection },
    TelescopeMultiSelection = { fg = c.type_ },
    TelescopeMultiIcon      = { fg = c.accent },
  })

  -- ─── Snacks.nvim ──────────────────────────────────────────────────────────
  set({
    SnacksNormal          = { fg = c.fg,      bg = c.bg2 },
    SnacksNormalNC        = { fg = c.fg1,     bg = c.bg2 },
    SnacksWinBar          = { fg = c.fg2,     bg = c.bg1 },
    SnacksWinBarNC        = { fg = c.fg3,     bg = c.bg1 },
    SnacksScratchTitle    = { fg = c.accent,  bold = true },
    SnacksScratchFooter   = { fg = c.fg3 },
    SnacksDashboardNormal = { fg = c.fg,      bg = c.bg },
    SnacksDashboardDesc   = { fg = c.fg1 },
    SnacksDashboardFile   = { fg = c.info },
    SnacksDashboardDir    = { fg = c.fg2 },
    SnacksDashboardDate   = { fg = c.fg3 },
    SnacksDashboardFooter = { fg = c.fg4 },
    SnacksDashboardHeader = { fg = c.accent },
    SnacksDashboardIcon   = { fg = c.accent2 },
    SnacksDashboardKey    = { fg = c.type_,   bold = true },
    SnacksDashboardTerminal = { fg = c.fn },
    SnacksDashboardSpecial = { fg = c.attr },
    SnacksDashboardTitle  = { fg = c.accent,  bold = true },
    SnacksIndent          = { fg = c.bg4 },
    SnacksIndentScope     = { fg = c.accent },
    SnacksZenSideBar      = { fg = c.fg4,     bg = c.bg },
    SnacksNotifierInfo    = { fg = c.info },
    SnacksNotifierWarn    = { fg = c.warn },
    SnacksNotifierError   = { fg = c.error_ },
    SnacksNotifierDebug   = { fg = c.fg2 },
    SnacksNotifierTrace   = { fg = c.fg3 },
    SnacksNotifierBorderInfo  = { fg = c.info },
    SnacksNotifierBorderWarn  = { fg = c.warn },
    SnacksNotifierBorderError = { fg = c.error_ },
    SnacksNotifierBorderDebug = { fg = c.fg3 },
    SnacksNotifierBorderTrace = { fg = c.fg4 },
    SnacksNotifierIconInfo  = { fg = c.info },
    SnacksNotifierIconWarn  = { fg = c.warn },
    SnacksNotifierIconError = { fg = c.error_ },
    SnacksNotifierIconDebug = { fg = c.fg2 },
    SnacksNotifierIconTrace = { fg = c.fg3 },
    SnacksPickerNormal    = { fg = c.fg,      bg = c.bg2 },
    SnacksPickerBorder    = { fg = c.bg4,     bg = c.bg2 },
    SnacksPickerTitle     = { fg = c.accent,  bg = c.bg2, bold = true },
    SnacksPickerMatch     = { fg = c.accent2, bold = true },
  })

  -- ─── neo-tree ─────────────────────────────────────────────────────────────
  set({
    NeoTreeNormal          = { fg = c.fg,     bg = c.bg1 },
    NeoTreeNormalNC        = { fg = c.fg1,    bg = c.bg1 },
    NeoTreeFloatNormal     = { fg = c.fg,     bg = c.bg2 },
    NeoTreeFloatBorder     = { fg = c.bg4,    bg = c.bg2 },
    NeoTreeFloatTitle      = { fg = c.accent, bg = c.bg2, bold = true },
    NeoTreeVertSplit       = { fg = c.bg4,    bg = c.bg1 },
    NeoTreeWinSeparator    = { fg = c.bg4,    bg = c.bg1 },
    NeoTreeEndOfBuffer     = { fg = c.bg1,    bg = c.bg1 },
    NeoTreeRootName        = { fg = c.accent, bold = true },
    NeoTreeFileName        = { fg = c.fg },
    NeoTreeFileNameOpened  = { fg = c.accent2 },
    NeoTreeFileIcon        = { fg = c.info },
    NeoTreeFileStats       = { fg = c.fg3 },
    NeoTreeFileStatsHeader = { fg = c.fg2,    bold = true },
    NeoTreeDirectoryName   = { fg = c.fn },
    NeoTreeDirectoryIcon   = { fg = c.info },
    NeoTreeSymbolicLinkTarget = { fg = c.type_ },
    NeoTreeGitAdded        = { fg = c.git_add },
    NeoTreeGitConflict     = { fg = c.warn },
    NeoTreeGitDeleted      = { fg = c.git_delete },
    NeoTreeGitIgnored      = { fg = c.fg4 },
    NeoTreeGitModified     = { fg = c.git_change },
    NeoTreeGitUnstaged     = { fg = c.git_change },
    NeoTreeGitUntracked    = { fg = c.fg2 },
    NeoTreeGitStaged       = { fg = c.git_add },
    NeoTreeIndentMarker    = { fg = c.bg5 },
    NeoTreeExpander        = { fg = c.fg3 },
    NeoTreeDotfile         = { fg = c.fg3 },
    NeoTreeHiddenByName    = { fg = c.fg4 },
    NeoTreeFilterTerm      = { fg = c.string_ },
    NeoTreeModified        = { fg = c.git_change },
    NeoTreeDimText         = { fg = c.fg4 },
    NeoTreeTabInactive     = { fg = c.fg3,    bg = c.bg1 },
    NeoTreeTabActive       = { fg = c.fg,     bg = c.bg },
    NeoTreeTabSeparatorActive   = { fg = c.accent },
    NeoTreeTabSeparatorInactive = { fg = c.bg4 },
  })

  -- ─── nvim-tree ────────────────────────────────────────────────────────────
  set({
    NvimTreeNormal          = { fg = c.fg,     bg = c.bg1 },
    NvimTreeNormalFloat     = { fg = c.fg,     bg = c.bg2 },
    NvimTreeWinSeparator    = { fg = c.bg4,    bg = c.bg1 },
    NvimTreeEndOfBuffer     = { fg = c.bg1 },
    NvimTreeRootFolder      = { fg = c.accent, bold = true },
    NvimTreeGitDirty        = { fg = c.git_change },
    NvimTreeGitNew          = { fg = c.git_add },
    NvimTreeGitDeleted      = { fg = c.git_delete },
    NvimTreeGitStaged       = { fg = c.git_add },
    NvimTreeGitMerge        = { fg = c.warn },
    NvimTreeGitRenamed      = { fg = c.info },
    NvimTreeGitUntracked    = { fg = c.fg3 },
    NvimTreeFolderName      = { fg = c.fn },
    NvimTreeOpenedFolderName= { fg = c.accent2 },
    NvimTreeEmptyFolderName = { fg = c.fg2 },
    NvimTreeFolderIcon      = { fg = c.info },
    NvimTreeFileIcon        = { fg = c.fg2 },
    NvimTreeSpecialFile     = { fg = c.attr },
    NvimTreeSymlink         = { fg = c.type_ },
    NvimTreeExecFile        = { fg = c.ok },
    NvimTreeIndentMarker    = { fg = c.bg5 },
    NvimTreeBookmark        = { fg = c.string_ },
    NvimTreeImageFile       = { fg = c.attr },
    NvimTreeCursorLine      = { bg = c.bg3 },
    NvimTreeLiveFilterValue = { fg = c.string_ },
    NvimTreeLiveFilterPrefix= { fg = c.accent, bold = true },
  })

  -- ─── which-key ────────────────────────────────────────────────────────────
  set({
    WhichKey          = { fg = c.accent2 },
    WhichKeyBorder    = { fg = c.bg4,   bg = c.bg2 },
    WhichKeyDesc      = { fg = c.fg },
    WhichKeyFloat     = { fg = c.fg,    bg = c.bg2 },
    WhichKeyGroup     = { fg = c.type_, bold = true },
    WhichKeyIcon      = { fg = c.attr },
    WhichKeyIconAzure = { fg = c.info },
    WhichKeyIconBlue  = { fg = c.fn },
    WhichKeyIconCyan  = { fg = c.hint },
    WhichKeyIconGreen = { fg = c.ok },
    WhichKeyIconGrey  = { fg = c.fg2 },
    WhichKeyIconOrange= { fg = c.warn },
    WhichKeyIconPurple= { fg = c.keyword },
    WhichKeyIconRed   = { fg = c.error_ },
    WhichKeyIconYellow= { fg = c.string_ },
    WhichKeyNormal    = { fg = c.fg,    bg = c.bg2 },
    WhichKeySeparator = { fg = c.fg3 },
    WhichKeyTitle     = { fg = c.accent, bold = true },
    WhichKeyValue     = { fg = c.string_ },
  })

  -- ─── indent-blankline / ibl ───────────────────────────────────────────────
  set({
    IblIndent       = { fg = c.bg4,   nocombine = true },
    IblScope        = { fg = c.bg5,   nocombine = true },
    IblWhitespace   = { fg = c.bg4,   nocombine = true },
    IndentBlanklineChar               = { fg = c.bg4,   nocombine = true },
    IndentBlanklineSpaceChar          = { fg = c.bg4,   nocombine = true },
    IndentBlanklineSpaceCharBlankline = { fg = c.bg4,   nocombine = true },
    IndentBlanklineContextChar        = { fg = c.accent, nocombine = true },
    IndentBlanklineContextStart       = { underline = true, sp = c.accent },
  })

  -- ─── Lualine (component colors) ───────────────────────────────────────────
  -- Exposed as named highlight groups so lualine config can reference them.
  set({
    LualineNormalA  = { fg = c.bg,     bg = c.accent,  bold = true },
    LualineNormalB  = { fg = c.fg,     bg = c.bg3 },
    LualineNormalC  = { fg = c.fg1,    bg = c.bg1 },
    LualineInsertA  = { fg = c.bg,     bg = c.fn,      bold = true },
    LualineInsertB  = { fg = c.fg,     bg = c.bg3 },
    LualineVisualA  = { fg = c.bg,     bg = c.attr,    bold = true },
    LualineVisualB  = { fg = c.fg,     bg = c.bg3 },
    LualineReplaceA = { fg = c.bg,     bg = c.error_,  bold = true },
    LualineReplaceB = { fg = c.fg,     bg = c.bg3 },
    LualineCommandA = { fg = c.bg,     bg = c.string_, bold = true },
    LualineCommandB = { fg = c.fg,     bg = c.bg3 },
    LualineInactive = { fg = c.fg3,    bg = c.bg1 },
  })

  -- ─── Bufferline ───────────────────────────────────────────────────────────
  set({
    BufferLineBackground     = { fg = c.fg2,    bg = c.bg1 },
    BufferLineBuffer         = { fg = c.fg2,    bg = c.bg1 },
    BufferLineBufferSelected = { fg = c.fg,     bg = c.bg, bold = true },
    BufferLineBufferVisible  = { fg = c.fg1,    bg = c.bg },
    BufferLineCloseButton    = { fg = c.fg3,    bg = c.bg1 },
    BufferLineCloseButtonSelected = { fg = c.error_, bg = c.bg },
    BufferLineCloseButtonVisible  = { fg = c.fg2,    bg = c.bg },
    BufferLineDiagnostic     = { fg = c.fg3,    bg = c.bg1 },
    BufferLineDiagnosticSelected = { fg = c.fg2, bg = c.bg },
    BufferLineError          = { fg = c.error_, bg = c.bg1 },
    BufferLineErrorSelected  = { fg = c.error_, bg = c.bg },
    BufferLineErrorDiagnostic = { fg = c.error_, bg = c.bg1 },
    BufferLineErrorDiagnosticSelected = { fg = c.error_, bg = c.bg },
    BufferLineWarning        = { fg = c.warn,   bg = c.bg1 },
    BufferLineWarningSelected= { fg = c.warn,   bg = c.bg },
    BufferLineInfo           = { fg = c.info,   bg = c.bg1 },
    BufferLineInfoSelected   = { fg = c.info,   bg = c.bg },
    BufferLineHint           = { fg = c.hint,   bg = c.bg1 },
    BufferLineHintSelected   = { fg = c.hint,   bg = c.bg },
    BufferLineModified       = { fg = c.git_change, bg = c.bg1 },
    BufferLineModifiedSelected = { fg = c.git_change, bg = c.bg },
    BufferLineModifiedVisible  = { fg = c.git_change, bg = c.bg },
    BufferLineDuplicate      = { fg = c.fg4,    bg = c.bg1 },
    BufferLineDuplicateSelected = { fg = c.fg3, bg = c.bg },
    BufferLineSeparator      = { fg = c.bg4,    bg = c.bg1 },
    BufferLineSeparatorSelected = { fg = c.bg4, bg = c.bg },
    BufferLineTab            = { fg = c.fg2,    bg = c.bg1 },
    BufferLineTabSelected    = { fg = c.accent, bg = c.bg, bold = true },
    BufferLineTabClose       = { fg = c.error_, bg = c.bg1 },
    BufferLineTabSeparator   = { fg = c.bg4,    bg = c.bg1 },
    BufferLineTabSeparatorSelected = { fg = c.accent, bg = c.bg },
    BufferLineFill           = { bg = c.bg1 },
    BufferLineIndicatorSelected = { fg = c.accent },
    BufferLineIndicatorVisible  = { fg = c.bg4 },
    BufferLineNumbers        = { fg = c.fg3,    bg = c.bg1 },
    BufferLineNumbersSelected = { fg = c.accent, bg = c.bg, bold = true },
    BufferLineNumbersVisible  = { fg = c.fg2,   bg = c.bg },
    BufferLinePick           = { fg = c.attr,   bg = c.bg1, bold = true },
    BufferLinePickSelected   = { fg = c.attr,   bg = c.bg,  bold = true },
    BufferLinePickVisible    = { fg = c.attr,   bg = c.bg },
    BufferLineGroupLabel     = { fg = c.bg,     bg = c.accent },
    BufferLineGroupSeparator = { fg = c.bg4,    bg = c.bg1 },
    BufferLineOffsetSeparator = { fg = c.bg4,   bg = c.bg },
    BufferLineTruncMarker    = { fg = c.fg3,    bg = c.bg1 },
  })

  -- ─── mini.nvim ────────────────────────────────────────────────────────────
  set({
    MiniAnimateCursor       = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat  = { link = "NormalFloat" },
    MiniClueBorder          = { link = "FloatBorder" },
    MiniClueDescGroup       = { fg = c.type_, bold = true },
    MiniClueDescSingle      = { fg = c.fg },
    MiniClueNextKey         = { fg = c.accent2, bold = true },
    MiniClueNextKeyWithPostkeys = { fg = c.attr, bold = true },
    MiniClueSeparator       = { fg = c.fg3 },
    MiniClueTitle           = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword          = { bg = c.bg3 },
    MiniCursorwordCurrent   = { bg = c.bg3 },
    MiniDepsChangeAdded     = { fg = c.git_add },
    MiniDepsChangeRemoved   = { fg = c.git_delete },
    MiniDepsHint            = { fg = c.hint },
    MiniDepsInfo            = { fg = c.info },
    MiniDepsMsgBreaking     = { fg = c.warn, bold = true },
    MiniDepsPlaceholder     = { fg = c.fg3 },
    MiniDepsTitle           = { fg = c.accent, bold = true },
    MiniDepsTitleError      = { fg = c.error_, bold = true },
    MiniDepsTitleSame       = { fg = c.fg2 },
    MiniDepsTitleUpdate     = { fg = c.ok, bold = true },
    MiniDiffSignAdd         = { fg = c.git_add },
    MiniDiffSignChange      = { fg = c.git_change },
    MiniDiffSignDelete      = { fg = c.git_delete },
    MiniDiffOverAdd         = { bg = "#0d1f14" },
    MiniDiffOverChange      = { bg = "#1c1708" },
    MiniDiffOverContext     = { bg = c.bg3 },
    MiniDiffOverDelete      = { bg = "#1f0d14" },
    MiniFilesBorder         = { link = "FloatBorder" },
    MiniFilesBorderModified = { fg = c.git_change },
    MiniFilesCursorLine     = { bg = c.bg3 },
    MiniFilesDirectory      = { fg = c.fn },
    MiniFilesFile           = { fg = c.fg },
    MiniFilesNormal         = { link = "NormalFloat" },
    MiniFilesTitle          = { link = "FloatTitle" },
    MiniFilesTitleFocused   = { fg = c.accent, bold = true },
    MiniHipatternsFixme     = { fg = c.bg, bg = c.error_, bold = true },
    MiniHipatternsHack      = { fg = c.bg, bg = c.warn,   bold = true },
    MiniHipatternsNote      = { fg = c.bg, bg = c.hint,   bold = true },
    MiniHipatternsTodo      = { fg = c.bg, bg = c.type_,  bold = true },
    MiniIconsAzure          = { fg = c.info },
    MiniIconsBlue           = { fg = c.fn },
    MiniIconsCyan           = { fg = c.hint },
    MiniIconsGreen          = { fg = c.ok },
    MiniIconsGrey           = { fg = c.fg2 },
    MiniIconsOrange         = { fg = c.warn },
    MiniIconsPurple         = { fg = c.keyword },
    MiniIconsRed            = { fg = c.error_ },
    MiniIconsYellow         = { fg = c.string_ },
    MiniIndentscopeSymbol   = { fg = c.accent },
    MiniIndentscopePrefix   = { nocombine = true },
    MiniJump                = { fg = c.bg, bg = c.accent2 },
    MiniJump2dDim           = { fg = c.fg4 },
    MiniJump2dSpot          = { fg = c.attr, bold = true, nocombine = true },
    MiniJump2dSpotAhead     = { fg = c.fn,   nocombine = true },
    MiniJump2dSpotUnique    = { fg = c.type_, bold = true, nocombine = true },
    MiniMapNormal           = { link = "NormalFloat" },
    MiniMapSymbolCount      = { fg = c.fg3 },
    MiniMapSymbolLine       = { fg = c.accent },
    MiniMapSymbolView       = { fg = c.type_ },
    MiniNotifyBorder        = { link = "FloatBorder" },
    MiniNotifyNormal        = { link = "NormalFloat" },
    MiniNotifyTitle         = { link = "FloatTitle" },
    MiniOperatorsplusCopyMarks = { fg = c.info },
    MiniPickBorder          = { link = "FloatBorder" },
    MiniPickBorderBusy      = { fg = c.warn },
    MiniPickBorderText      = { fg = c.accent },
    MiniPickHeader          = { fg = c.accent2, bold = true },
    MiniPickIconDirectory   = { fg = c.fn },
    MiniPickIconFile        = { fg = c.fg2 },
    MiniPickMatchCurrent    = { bg = c.selection },
    MiniPickMatchMarked     = { bg = c.bg3 },
    MiniPickMatchRanges     = { fg = c.accent2, bold = true },
    MiniPickNormal          = { link = "NormalFloat" },
    MiniPickPreviewLine     = { bg = c.bg3 },
    MiniPickPreviewRegion   = { bg = c.match },
    MiniPickPrompt          = { fg = c.accent2 },
    MiniStarterCurrent      = { nocombine = true },
    MiniStarterFooter       = { fg = c.fg3 },
    MiniStarterHeader       = { fg = c.accent },
    MiniStarterInactive     = { fg = c.fg4 },
    MiniStarterItem         = { fg = c.fg },
    MiniStarterItemBullet   = { fg = c.accent },
    MiniStarterItemPrefix   = { fg = c.attr },
    MiniStarterQuery        = { fg = c.fn },
    MiniStarterSection      = { fg = c.type_, bold = true },
    MiniStatuslineDevinfo   = { fg = c.fg2,    bg = c.bg3 },
    MiniStatuslineFileinfo  = { fg = c.fg2,    bg = c.bg3 },
    MiniStatuslineFilename  = { fg = c.fg1,    bg = c.bg1 },
    MiniStatuslineInactive  = { fg = c.fg3,    bg = c.bg1 },
    MiniStatuslineModeCommand = { fg = c.bg,   bg = c.string_, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg,   bg = c.fn,      bold = true },
    MiniStatuslineModeNormal  = { fg = c.bg,   bg = c.accent,  bold = true },
    MiniStatuslineModeOther   = { fg = c.bg,   bg = c.type_,   bold = true },
    MiniStatuslineModeReplace = { fg = c.bg,   bg = c.error_,  bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg,   bg = c.attr,    bold = true },
    MiniSurround            = { fg = c.bg, bg = c.accent },
    MiniTablineCurrent      = { fg = c.fg,  bg = c.bg, bold = true },
    MiniTablineFill         = { bg = c.bg1 },
    MiniTablineHidden       = { fg = c.fg3, bg = c.bg1 },
    MiniTablineModifiedCurrent = { fg = c.git_change, bg = c.bg, bold = true },
    MiniTablineModifiedHidden  = { fg = c.git_change, bg = c.bg1 },
    MiniTablineModifiedVisible = { fg = c.git_change, bg = c.bg },
    MiniTablineTabpagesection  = { fg = c.bg, bg = c.fg3 },
    MiniTablineVisible         = { fg = c.fg1, bg = c.bg },
    MiniTestEmphasis        = { bold = true },
    MiniTestFail            = { fg = c.error_, bold = true },
    MiniTestPass            = { fg = c.ok,     bold = true },
    MiniTrailspace          = { bg = c.error_ },
  })

  -- ─── noice.nvim ───────────────────────────────────────────────────────────
  set({
    NoiceCmdline         = { fg = c.fg,     bg = c.bg2 },
    NoiceCmdlineIcon     = { fg = c.accent },
    NoiceCmdlineIconSearch = { fg = c.string_ },
    NoiceCmdlinePopup    = { fg = c.fg,     bg = c.bg2 },
    NoiceCmdlinePopupBorder = { fg = c.bg4, bg = c.bg2 },
    NoiceCmdlinePopupBorderSearch = { fg = c.string_, bg = c.bg2 },
    NoiceCmdlinePopupTitle = { fg = c.accent, bold = true },
    NoiceConfirm         = { fg = c.fg,     bg = c.bg2 },
    NoiceConfirmBorder   = { fg = c.bg4,    bg = c.bg2 },
    NoiceFormatDate      = { fg = c.fg3 },
    NoiceFormatEvent     = { fg = c.fg4 },
    NoiceFormatKind      = { fg = c.hint },
    NoiceFormatLevelDebug = { fg = c.fg3 },
    NoiceFormatLevelError = { fg = c.error_ },
    NoiceFormatLevelInfo  = { fg = c.info },
    NoiceFormatLevelOff   = { fg = c.fg4 },
    NoiceFormatLevelTrace = { fg = c.fg4 },
    NoiceFormatLevelWarn  = { fg = c.warn },
    NoiceFormatProgressDone = { fg = c.ok },
    NoiceFormatProgressTodo = { fg = c.fg3 },
    NoiceFormatTitle     = { fg = c.accent, bold = true },
    NoiceLspProgressClient = { fg = c.accent2 },
    NoiceLspProgressSpinner = { fg = c.fn },
    NoiceLspProgressTitle  = { fg = c.fg1 },
    NoiceMini            = { fg = c.fg,     bg = c.bg2 },
    NoicePopup           = { fg = c.fg,     bg = c.bg2 },
    NoicePopupBorder     = { fg = c.bg4,    bg = c.bg2 },
    NoiceScrollbar       = { bg = c.bg3 },
    NoiceScrollbarThumb  = { bg = c.accent },
    NoiceSplit           = { fg = c.fg,     bg = c.bg },
    NoiceSplitBorder     = { fg = c.bg4 },
    NoiceVirtualText     = { fg = c.fg3 },
  })

  -- ─── nvim-notify ──────────────────────────────────────────────────────────
  set({
    NotifyBackground       = { bg = c.bg2 },
    NotifyERRORBorder      = { fg = c.error_, bg = c.bg2 },
    NotifyWARNBorder       = { fg = c.warn,   bg = c.bg2 },
    NotifyINFOBorder       = { fg = c.info,   bg = c.bg2 },
    NotifyDEBUGBorder      = { fg = c.fg3,    bg = c.bg2 },
    NotifyTRACEBorder      = { fg = c.fg4,    bg = c.bg2 },
    NotifyERRORIcon        = { fg = c.error_ },
    NotifyWARNIcon         = { fg = c.warn },
    NotifyINFOIcon         = { fg = c.info },
    NotifyDEBUGIcon        = { fg = c.fg3 },
    NotifyTRACEIcon        = { fg = c.fg4 },
    NotifyERRORTitle       = { fg = c.error_, bold = true },
    NotifyWARNTitle        = { fg = c.warn,   bold = true },
    NotifyINFOTitle        = { fg = c.info,   bold = true },
    NotifyDEBUGTitle       = { fg = c.fg3,    bold = true },
    NotifyTRACETitle       = { fg = c.fg4,    bold = true },
    NotifyERRORBody        = { fg = c.fg,     bg = c.bg2 },
    NotifyWARNBody         = { fg = c.fg,     bg = c.bg2 },
    NotifyINFOBody         = { fg = c.fg,     bg = c.bg2 },
    NotifyDEBUGBody        = { fg = c.fg,     bg = c.bg2 },
    NotifyTRACEBody        = { fg = c.fg,     bg = c.bg2 },
  })

  -- ─── nvim-dap / nvim-dap-ui ───────────────────────────────────────────────
  set({
    DapBreakpoint          = { fg = c.error_ },
    DapBreakpointCondition = { fg = c.warn },
    DapBreakpointRejected  = { fg = c.fg3 },
    DapLogPoint            = { fg = c.info },
    DapStopped             = { fg = c.ok },
    DapStoppedLine         = { bg = "#0d1f14" },
    DapUIBreakpointsCurrentLine = { fg = c.ok, bold = true },
    DapUIBreakpointsDisabledLine = { fg = c.fg3 },
    DapUIBreakpointsInfo   = { fg = c.info },
    DapUIBreakpointsLine   = { fg = c.number },
    DapUIBreakpointsPath   = { fg = c.info },
    DapUIDecoration        = { fg = c.bg4 },
    DapUIEndofBuffer       = { fg = c.bg1 },
    DapUIFloatBorder       = { fg = c.bg4 },
    DapUIFloatNormal       = { link = "NormalFloat" },
    DapUIFrameName         = { fg = c.fn },
    DapUILineNumber        = { fg = c.number },
    DapUIModifiedValue     = { fg = c.warn, bold = true },
    DapUINormalNC          = { fg = c.fg1 },
    DapUIPlayPause         = { fg = c.ok },
    DapUIRestart           = { fg = c.ok },
    DapUIScope             = { fg = c.type_ },
    DapUISource            = { fg = c.type_ },
    DapUIStepBack          = { fg = c.fn },
    DapUIStepInto          = { fg = c.fn },
    DapUIStepOut           = { fg = c.fn },
    DapUIStepOver          = { fg = c.fn },
    DapUIStop              = { fg = c.error_ },
    DapUIStoppedThread     = { fg = c.accent },
    DapUIThread            = { fg = c.accent2 },
    DapUIType              = { link = "Type" },
    DapUIUnavailable       = { fg = c.fg3 },
    DapUIValue             = { fg = c.fg },
    DapUIVariable          = { fg = c.variable },
    DapUIWatchesEmpty      = { fg = c.error_ },
    DapUIWatchesError      = { fg = c.error_ },
    DapUIWatchesValue      = { fg = c.ok },
    DapUIWinSelect         = { fg = c.accent2, bold = true },
    DapVirtualText         = { fg = c.fg3, italic = true },
  })

  -- ─── lazy.nvim ────────────────────────────────────────────────────────────
  set({
    LazyBold        = { bold = true },
    LazyButton      = { fg = c.fg,     bg = c.bg3 },
    LazyButtonActive= { fg = c.fg,     bg = c.selection, bold = true },
    LazyComment     = { fg = c.fg3 },
    LazyCommit      = { fg = c.fn },
    LazyCommitBorder= { fg = c.bg4 },
    LazyCommitIssue = { fg = c.number },
    LazyCommitScope = { fg = c.type_,  italic = true },
    LazyCommitType  = { fg = c.keyword, bold = true },
    LazyDimmed      = { fg = c.fg4 },
    LazyDir         = { fg = c.info },
    LazyError       = { fg = c.error_ },
    LazyH1          = { fg = c.bg,     bg = c.accent, bold = true },
    LazyH2          = { fg = c.accent, bold = true },
    LazyHandlerCmd  = { fg = c.fn },
    LazyHandlerEvent= { fg = c.attr },
    LazyHandlerFt   = { fg = c.type_ },
    LazyHandlerKeys = { fg = c.accent2 },
    LazyHandlerPlugin = { fg = c.accent },
    LazyHandlerRuntime = { fg = c.warn },
    LazyHandlerSource = { fg = c.string_ },
    LazyHandlerStart= { fg = c.ok },
    LazyItalic      = { italic = true },
    LazyLocal       = { fg = c.ok },
    LazyNoCond      = { fg = c.fg4 },
    LazyNormal      = { fg = c.fg,     bg = c.bg2 },
    LazyProgressDone = { fg = c.ok },
    LazyProgressTodo = { fg = c.fg3 },
    LazyProp        = { fg = c.fg2 },
    LazyReasonCmd   = { fg = c.fn },
    LazyReasonEvent = { fg = c.attr },
    LazyReasonFt    = { fg = c.type_ },
    LazyReasonImport= { fg = c.accent },
    LazyReasonKeys  = { fg = c.accent2 },
    LazyReasonPlugin= { fg = c.accent },
    LazyReasonRequire = { fg = c.keyword },
    LazyReasonRuntime = { fg = c.warn },
    LazyReasonSource= { fg = c.string_ },
    LazyReasonStart = { fg = c.ok },
    LazySpecial     = { fg = c.attr },
    LazyStatsHeader = { fg = c.accent, bold = true },
    LazyTaskError   = { fg = c.error_ },
    LazyTaskOutput  = { fg = c.fg2 },
    LazyTitle       = { fg = c.accent, bold = true },
    LazyUrl         = { fg = c.info,   underline = true },
    LazyValue       = { fg = c.string_ },
    LazyWarning     = { fg = c.warn },
  })

  -- ─── mason.nvim ───────────────────────────────────────────────────────────
  set({
    MasonError              = { fg = c.error_ },
    MasonHeader             = { fg = c.bg, bg = c.accent, bold = true },
    MasonHeaderSecondary    = { fg = c.bg, bg = c.fn,     bold = true },
    MasonHeading            = { fg = c.accent, bold = true },
    MasonHighlight          = { fg = c.fn },
    MasonHighlightBlock     = { fg = c.bg, bg = c.fn },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.fn, bold = true },
    MasonHighlightBlockBoldSecondary = { fg = c.bg, bg = c.type_, bold = true },
    MasonHighlightBlockSecondary     = { fg = c.bg, bg = c.type_ },
    MasonHighlightSecondary = { fg = c.type_ },
    MasonLink               = { fg = c.info,   underline = true },
    MasonMuted              = { fg = c.fg3 },
    MasonMutedBlock         = { fg = c.fg3,    bg = c.bg3 },
    MasonMutedBlockBold     = { fg = c.fg2,    bg = c.bg3, bold = true },
    MasonNormal             = { fg = c.fg,     bg = c.bg2 },
    MasonWarning            = { fg = c.warn },
  })

  -- ─── nvim-dap-virtual-text / nvim-treesitter-context ─────────────────────
  set({
    TreesitterContext            = { bg = c.bg1 },
    TreesitterContextLineNumber  = { fg = c.linenr, bg = c.bg1 },
    TreesitterContextSeparator   = { fg = c.bg4 },
    TreesitterContextBottom      = { underline = true, sp = c.bg4 },
  })

  -- ─── Aerial ───────────────────────────────────────────────────────────────
  set({
    AerialNormal    = { fg = c.fg,     bg = c.bg1 },
    AerialLine      = { bg = c.selection },
    AerialLineNC    = { bg = c.bg3 },
    AerialGuide     = { fg = c.bg4 },
    AerialClass     = { link = "Type" },
    AerialFunction  = { link = "Function" },
    AerialMethod    = { link = "Function" },
    AerialField     = { fg = c.field },
    AerialVariable  = { fg = c.variable },
    AerialConstant  = { link = "Constant" },
    AerialConstructor = { link = "@constructor" },
    AerialEnum      = { link = "Type" },
    AerialInterface = { fg = c.type_ },
    AerialModule    = { fg = c.namespace },
    AerialNamespace = { fg = c.namespace },
    AerialPackage   = { fg = c.namespace },
    AerialStruct    = { link = "Type" },
    AerialKey       = { fg = c.field },
    AerialString    = { link = "String" },
    AerialNumber    = { link = "Number" },
    AerialBoolean   = { link = "Boolean" },
    AerialArray     = { fg = c.punct },
    AerialObject    = { fg = c.type_ },
    AerialOperator  = { link = "Operator" },
    AerialTypeParameter = { fg = c.type_ },
  })

  -- ─── nvim-surround / vim-surround ─────────────────────────────────────────
  set({
    SurroundHighlight  = { fg = c.bg, bg = c.accent },
    MatchWord          = { bold = true },
    MatchWordCur       = { bold = true },
  })

  -- ─── flash.nvim ───────────────────────────────────────────────────────────
  set({
    FlashBackdrop  = { fg = c.fg4 },
    FlashLabel     = { fg = c.bg, bg = c.attr,   bold = true },
    FlashMatch     = { fg = c.accent2, bg = c.match },
    FlashCurrent   = { fg = c.bg, bg = c.accent2, bold = true },
    FlashCursor    = { reverse = true },
    FlashPrompt    = { fg = c.accent2, bold = true },
    FlashPromptIcon= { fg = c.accent },
    FlashChar      = { fg = c.bg, bg = c.attr,   bold = true },
    FlashCharHint  = { fg = c.bg, bg = c.type_,  bold = true },
  })

  -- ─── leap.nvim ────────────────────────────────────────────────────────────
  set({
    LeapMatch       = { fg = c.bg, bg = c.accent2 },
    LeapLabelPrimary= { fg = c.bg, bg = c.attr, bold = true },
    LeapLabelSecondary = { fg = c.bg, bg = c.type_ },
    LeapBackdrop    = { fg = c.fg4 },
  })

  -- ─── todo-comments ────────────────────────────────────────────────────────
  set({
    TodoFgFIX   = { fg = c.error_ },
    TodoFgHACK  = { fg = c.warn },
    TodoFgNOTE  = { fg = c.hint },
    TodoFgPERF  = { fg = c.fn },
    TodoFgTEST  = { fg = c.attr },
    TodoFgTODO  = { fg = c.type_ },
    TodoFgWARN  = { fg = c.warn },
    TodoBgFIX   = { fg = c.bg, bg = c.error_, bold = true },
    TodoBgHACK  = { fg = c.bg, bg = c.warn,   bold = true },
    TodoBgNOTE  = { fg = c.bg, bg = c.hint,   bold = true },
    TodoBgPERF  = { fg = c.bg, bg = c.fn,     bold = true },
    TodoBgTEST  = { fg = c.bg, bg = c.attr,   bold = true },
    TodoBgTODO  = { fg = c.bg, bg = c.type_,  bold = true },
    TodoBgWARN  = { fg = c.bg, bg = c.warn,   bold = true },
    TodoSignFIX = { link = "TodoFgFIX" },
    TodoSignHACK= { link = "TodoFgHACK" },
    TodoSignNOTE= { link = "TodoFgNOTE" },
    TodoSignPERF= { link = "TodoFgPERF" },
    TodoSignTEST= { link = "TodoFgTEST" },
    TodoSignTODO= { link = "TodoFgTODO" },
    TodoSignWARN= { link = "TodoFgWARN" },
  })

  -- ─── headlines.nvim ───────────────────────────────────────────────────────
  set({
    Headline1 = { bg = "#1a1530" },
    Headline2 = { bg = "#141f1c" },
    Headline3 = { bg = "#1a170d" },
    Headline4 = { bg = "#1a1118" },
    Headline5 = { bg = "#171a10" },
    Headline6 = { bg = "#101620" },
    CodeBlock = { bg = c.bg3 },
    Quote     = { fg = c.fg2 },
    Dash      = { fg = c.bg5 },
  })

  -- ─── render-markdown.nvim ─────────────────────────────────────────────────
  set({
    RenderMarkdownH1        = { fg = c.accent,   bold = true },
    RenderMarkdownH2        = { fg = c.fn,       bold = true },
    RenderMarkdownH3        = { fg = c.type_,    bold = true },
    RenderMarkdownH4        = { fg = c.string_,  bold = true },
    RenderMarkdownH5        = { fg = c.number,   bold = true },
    RenderMarkdownH6        = { fg = c.fg1,      bold = true },
    RenderMarkdownH1Bg      = { bg = "#1a1530" },
    RenderMarkdownH2Bg      = { bg = "#141f1c" },
    RenderMarkdownH3Bg      = { bg = "#1a170d" },
    RenderMarkdownH4Bg      = { bg = "#1a1118" },
    RenderMarkdownH5Bg      = { bg = "#171a10" },
    RenderMarkdownH6Bg      = { bg = "#101620" },
    RenderMarkdownCode      = { bg = c.bg3 },
    RenderMarkdownCodeInline= { fg = c.string_,  bg = c.bg3 },
    RenderMarkdownBullet    = { fg = c.accent },
    RenderMarkdownDash      = { fg = c.bg5 },
    RenderMarkdownLink      = { fg = c.info,     underline = true },
    RenderMarkdownWikiLink  = { fg = c.accent2,  underline = true },
    RenderMarkdownMath      = { fg = c.number },
    RenderMarkdownQuote     = { fg = c.fg2,      italic = true },
    RenderMarkdownTableHead = { fg = c.accent,   bold = true },
    RenderMarkdownTableRow  = { fg = c.fg },
    RenderMarkdownTableFill = { fg = c.bg4 },
    RenderMarkdownChecked   = { fg = c.ok },
    RenderMarkdownUnchecked = { fg = c.fg3 },
    RenderMarkdownTodo      = { fg = c.bg, bg = c.type_,  bold = true },
    RenderMarkdownSuccess   = { fg = c.ok },
    RenderMarkdownInfo      = { fg = c.info },
    RenderMarkdownWarn      = { fg = c.warn },
    RenderMarkdownError     = { fg = c.error_ },
    RenderMarkdownHint      = { fg = c.hint },
  })

  -- ─── Trouble ──────────────────────────────────────────────────────────────
  set({
    TroubleNormal       = { fg = c.fg,    bg = c.bg1 },
    TroubleNormalNC     = { fg = c.fg1,   bg = c.bg1 },
    TroubleCount        = { fg = c.accent, bold = true },
    TroubleError        = { fg = c.error_ },
    TroubleWarn         = { fg = c.warn },
    TroubleInfo         = { fg = c.info },
    TroubleHint         = { fg = c.hint },
    TroubleFileName     = { fg = c.info },
    TroubleLocation     = { fg = c.fg3 },
    TroubleFoldIcon     = { fg = c.fg2 },
    TroubleCode         = { fg = c.fg3 },
    TroubleSignError    = { fg = c.error_ },
    TroubleSignWarning  = { fg = c.warn },
    TroubleSignHint     = { fg = c.hint },
    TroubleSignInformation = { fg = c.info },
    TroubleText         = { fg = c.fg },
    TroubleTextError    = { fg = c.error_ },
    TroubleTextWarning  = { fg = c.warn },
    TroubleTextHint     = { fg = c.hint },
    TroubleTextInformation = { fg = c.info },
    TroubleSource       = { fg = c.fn },
    TroubleIndent       = { fg = c.bg4 },
    TroublePos          = { fg = c.number },
    TroublePreview      = { bg = c.bg3 },
  })

  -- ─── nvim-ufo (folding) ───────────────────────────────────────────────────
  set({
    UfoFoldedEllipsis = { fg = c.fg3 },
    UfoCursorFoldedLine = { bg = c.bg3, bold = true },
  })

  -- ─── yanky.nvim ───────────────────────────────────────────────────────────
  set({
    YankyPut         = { fg = c.bg, bg = c.ok },
    YankyYanked      = { fg = c.bg, bg = c.string_ },
  })

  -- ─── vim-illuminate ───────────────────────────────────────────────────────
  set({
    IlluminatedWordText  = { bg = c.bg3 },
    IlluminatedWordRead  = { bg = c.bg3 },
    IlluminatedWordWrite = { bg = c.bg3, underline = true },
  })

  -- ─── nvim-scrollbar ───────────────────────────────────────────────────────
  set({
    ScrollbarHandle    = { bg = c.bg3 },
    ScrollbarCursor    = { fg = c.accent,  bg = c.bg3 },
    ScrollbarSearch    = { fg = c.string_, bg = c.bg3 },
    ScrollbarError     = { fg = c.error_,  bg = c.bg3 },
    ScrollbarWarn      = { fg = c.warn,    bg = c.bg3 },
    ScrollbarInfo      = { fg = c.info,    bg = c.bg3 },
    ScrollbarHint      = { fg = c.hint,    bg = c.bg3 },
    ScrollbarMisc      = { fg = c.fg3,     bg = c.bg3 },
    ScrollbarGitAdd    = { fg = c.git_add, bg = c.bg3 },
    ScrollbarGitChange = { fg = c.git_change, bg = c.bg3 },
    ScrollbarGitDelete = { fg = c.git_delete, bg = c.bg3 },
  })

  -- ─── Terminal colors ──────────────────────────────────────────────────────
  local tc = c.term
  vim.g.terminal_color_0  = tc.black
  vim.g.terminal_color_1  = tc.red
  vim.g.terminal_color_2  = tc.green
  vim.g.terminal_color_3  = tc.yellow
  vim.g.terminal_color_4  = tc.blue
  vim.g.terminal_color_5  = tc.magenta
  vim.g.terminal_color_6  = tc.cyan
  vim.g.terminal_color_7  = tc.white
  vim.g.terminal_color_8  = tc.bright_black
  vim.g.terminal_color_9  = tc.bright_red
  vim.g.terminal_color_10 = tc.bright_green
  vim.g.terminal_color_11 = tc.bright_yellow
  vim.g.terminal_color_12 = tc.bright_blue
  vim.g.terminal_color_13 = tc.bright_magenta
  vim.g.terminal_color_14 = tc.bright_cyan
  vim.g.terminal_color_15 = tc.bright_white
end

return M
