[colors.primary]
background = "#000000"
foreground = "#faf4ed"
dim_foreground = "#6e6a86"
bright_foreground = "#e0def4"

[colors.cursor]
text   = "#000000"
cursor = "#908caa"

[colors.vi_mode_cursor]
text   = "#000000"
cursor = "#3e8fb0"

[colors.search.matches]
foreground = "#e0def4"
background = "#2a283e"

[colors.search.focused_match]
foreground = "#000000"
background = "#908caa"

[colors.hints.start]
foreground = "#000000"
background = "#f6c177"

[colors.hints.end]
foreground = "#000000"
background = "#9ccfd8"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#000000"
background = "#908caa"

[colors.selection]
text       = "CellForeground"
background = "#2a283e"

[colors.normal]
black   = "#000000"
red     = "#eb6f92"
green   = "#6ed48a"
yellow  = "#f6c177"
blue    = "#3e8fb0"
magenta = "#c4a7e7"
cyan    = "#9ccfd8"
white   = "#e0def4"

[colors.bright]
black   = "#6e6a86"
red     = "#eb6f92"
green   = "#90e4a8"
yellow  = "#f6c177"
blue    = "#3e8fb0"
magenta = "#c4a7e7"
cyan    = "#9ccfd8"
white   = "#faf4ed"

[colors.dim]
black   = "#0d0d14"
red     = "#a84d68"
green   = "#4ea068"
yellow  = "#b08830"
blue    = "#2a6880"
magenta = "#8068b0"
cyan    = "#5090a0"
white   = "#6e6a86"
